---
version: 0.2
environment_variables:
  plaintext:
    NG_CLI_ANALYTICS: "false"
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install -g @angular/cli
      - npm ci
  build:
    commands:
      - ng build --configuration=$ENV --aot --output-hashing=all
  post_build:
    commands:
      - aws s3 sync dist/ s3://$BUCKET --exclude index.html --cache-control max-age=31536000
      - aws s3 cp dist/index.html s3://$BUCKET/index.html --metadata-directive REPLACE --cache-control max-age=60
      - aws s3 cp dist/assets/i18n/ s3://$BUCKET/assets/i18n/ --recursive --metadata-directive REPLACE --cache-control max-age=3600
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT --paths /index.html /assets/i18n/*
